-- Create DATA 607 Skills of a Data Scientist Project Database

-- Step 1: Create the new database

DROP DATABASE IF EXISTS `DATA607`;

CREATE SCHEMA `DATA607` DEFAULT CHARACTER SET utf8 ;

-- Step 2: Create the tables

-- Locations

DROP TABLE IF EXISTS `DATA607`.`LOCATIONS`;

CREATE TABLE `DATA607`.`LOCATIONS` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
);

-- Indeed Raw HTML

DROP TABLE IF EXISTS `DATA607`.`INDEED_RAW_HTML`;

CREATE TABLE `DATA607`.`INDEED_RAW_HTML` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `LOCATIONS_id` INT UNSIGNED NOT NULL,
    `url` VARCHAR(255) NOT NULL,
    `html` TEXT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);